{{- if not .Values.database.existingSecret.enabled }}
{{- if or .Values.database.password .Values.auth.workerPassword .Values.auth.adminPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fish-fry-orders.fullname" . }}-secret
  labels:
    {{- include "fish-fry-orders.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.database.password }}
  db-password: {{ .Values.database.password | quote }}
  {{- end }}
  {{- if not .Values.auth.existingSecret.enabled }}
  {{- if .Values.auth.workerPassword }}
  auth-worker-password: {{ .Values.auth.workerPassword | quote }}
  {{- end }}
  {{- if .Values.auth.adminPassword }}
  auth-admin-password: {{ .Values.auth.adminPassword | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
