apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fish-fry-orders-v2.fullname" . }}-config
  labels:
    {{- include "fish-fry-orders-v2.labels" . | nindent 4 }}
data:
  config.yaml: |
    # Database and auth configs loaded from secrets at /app/secrets/

    redis:
      enabled: {{ .Values.redis.enabled }}
      host: {{ .Values.redis.host | quote }}
      port: {{ .Values.redis.port }}
      password: {{ .Values.redis.password | quote }}
      db: {{ .Values.redis.db }}

    http:
      address: ":8080"

    grpc:
      address: ":50051"
