// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/orders.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Order status
type OrderStatus int32

const (
	OrderStatus_NEW         OrderStatus = 0
	OrderStatus_IN_PROGRESS OrderStatus = 1
	OrderStatus_COMPLETED   OrderStatus = 2
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "NEW",
		1: "IN_PROGRESS",
		2: "COMPLETED",
	}
	OrderStatus_value = map[string]int32{
		"NEW":         0,
		"IN_PROGRESS": 1,
		"COMPLETED":   2,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_orders_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_proto_orders_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_orders_proto_rawDescGZIP(), []int{0}
}

// Menu item
type MenuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItem) Reset() {
	*x = MenuItem{}
	mi := &file_proto_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItem) ProtoMessage() {}

func (x *MenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItem.ProtoReflect.Descriptor instead.
func (*MenuItem) Descriptor() ([]byte, []int) {
	return file_proto_orders_proto_rawDescGZIP(), []int{0}
}

func (x *MenuItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MenuItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MenuItem) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// Order item
type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuItemId    string                 `protobuf:"bytes,1,opt,name=menu_item_id,json=menuItemId,proto3" json:"menu_item_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_proto_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_proto_orders_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetMenuItemId() string {
	if x != nil {
		return x.MenuItemId
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// Order
type Order struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VehicleDescription string                 `protobuf:"bytes,2,opt,name=vehicle_description,json=vehicleDescription,proto3" json:"vehicle_description,omitempty"`
	Items              []*OrderItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Status             OrderStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=orders.OrderStatus" json:"status,omitempty"`
	CreatedAt          int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_orders_proto_rawDescGZIP(), []int{2}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetVehicleDescription() string {
	if x != nil {
		return x.VehicleDescription
	}
	return ""
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_NEW
}

func (x *Order) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Order) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// Chat message
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	SenderRole    string                 `protobuf:"bytes,4,opt,name=sender_role,json=senderRole,proto3" json:"sender_role,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_orders_proto_rawDescGZIP(), []int{3}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetSenderRole() string {
	if x != nil {
		return x.SenderRole
	}
	return ""
}

func (x *ChatMessage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// Statistics
type OrderStatistics struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ItemCounts            map[string]int32       `protobuf:"bytes,1,rep,name=item_counts,json=itemCounts,proto3" json:"item_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	AverageCompletionTime float64                `protobuf:"fixed64,2,opt,name=average_completion_time,json=averageCompletionTime,proto3" json:"average_completion_time,omitempty"`
	TotalOrders           int32                  `protobuf:"varint,3,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *OrderStatistics) Reset() {
	*x = OrderStatistics{}
	mi := &file_proto_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatistics) ProtoMessage() {}

func (x *OrderStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatistics.ProtoReflect.Descriptor instead.
func (*OrderStatistics) Descriptor() ([]byte, []int) {
	return file_proto_orders_proto_rawDescGZIP(), []int{4}
}

func (x *OrderStatistics) GetItemCounts() map[string]int32 {
	if x != nil {
		return x.ItemCounts
	}
	return nil
}

func (x *OrderStatistics) GetAverageCompletionTime() float64 {
	if x != nil {
		return x.AverageCompletionTime
	}
	return 0
}

func (x *OrderStatistics) GetTotalOrders() int32 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

// Request/Response messages
type CreateOrderRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	VehicleDescription string                 `protobuf:"bytes,1,opt,name=vehicle_description,json=vehicleDescription,proto3" json:"vehicle_description,omitempty"`
	Items              []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_proto_orders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_orders_proto_rawDescGZIP(), []int{5}
}

func (x *CreateOrderRequest) GetVehicleDescription() string {
	if x != nil {
		return x.VehicleDescription
	}
	return ""
}

func (x *CreateOrderRequest) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=orders.OrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_proto_orders_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusRequest) ProtoMessage() {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_orders_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateOrderStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_NEW
}

type GetOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusFilter  string                 `protobuf:"bytes,1,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersRequest) Reset() {
	*x = GetOrdersRequest{}
	mi := &file_proto_orders_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersRequest) ProtoMessage() {}

func (x *GetOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersRequest) Descriptor() ([]byte, []int) {
	return file_proto_orders_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrdersRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	SenderRole    string                 `protobuf:"bytes,3,opt,name=sender_role,json=senderRole,proto3" json:"sender_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_proto_orders_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_orders_proto_rawDescGZIP(), []int{8}
}

func (x *SendMessageRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetSenderRole() string {
	if x != nil {
		return x.SenderRole
	}
	return ""
}

type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_proto_orders_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_orders_proto_rawDescGZIP(), []int{9}
}

func (x *GetMessagesRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     int64                  `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsRequest) Reset() {
	*x = GetStatisticsRequest{}
	mi := &file_proto_orders_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsRequest) ProtoMessage() {}

func (x *GetStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_orders_proto_rawDescGZIP(), []int{10}
}

func (x *GetStatisticsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetStatisticsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type GetMenuItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuItemsRequest) Reset() {
	*x = GetMenuItemsRequest{}
	mi := &file_proto_orders_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemsRequest) ProtoMessage() {}

func (x *GetMenuItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemsRequest.ProtoReflect.Descriptor instead.
func (*GetMenuItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_orders_proto_rawDescGZIP(), []int{11}
}

type GetMenuItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MenuItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuItemsResponse) Reset() {
	*x = GetMenuItemsResponse{}
	mi := &file_proto_orders_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemsResponse) ProtoMessage() {}

func (x *GetMenuItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemsResponse.ProtoReflect.Descriptor instead.
func (*GetMenuItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_orders_proto_rawDescGZIP(), []int{12}
}

func (x *GetMenuItemsResponse) GetItems() []*MenuItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *MenuItem              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuItemRequest) Reset() {
	*x = UpdateMenuItemRequest{}
	mi := &file_proto_orders_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuItemRequest) ProtoMessage() {}

func (x *UpdateMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_orders_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateMenuItemRequest) GetItem() *MenuItem {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_proto_orders_proto protoreflect.FileDescriptor

const file_proto_orders_proto_rawDesc = "" +
	"\n" +
	"\x12proto/orders.proto\x12\x06orders\"a\n" +
	"\bMenuItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\"I\n" +
	"\tOrderItem\x12 \n" +
	"\fmenu_item_id\x18\x01 \x01(\tR\n" +
	"menuItemId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\xdc\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x13vehicle_description\x18\x02 \x01(\tR\x12vehicleDescription\x12'\n" +
	"\x05items\x18\x03 \x03(\v2\x11.orders.OrderItemR\x05items\x12+\n" +
	"\x06status\x18\x04 \x01(\x0e2\x13.orders.OrderStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"\x92\x01\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1f\n" +
	"\vsender_role\x18\x04 \x01(\tR\n" +
	"senderRole\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"\xf5\x01\n" +
	"\x0fOrderStatistics\x12H\n" +
	"\vitem_counts\x18\x01 \x03(\v2'.orders.OrderStatistics.ItemCountsEntryR\n" +
	"itemCounts\x126\n" +
	"\x17average_completion_time\x18\x02 \x01(\x01R\x15averageCompletionTime\x12!\n" +
	"\ftotal_orders\x18\x03 \x01(\x05R\vtotalOrders\x1a=\n" +
	"\x0fItemCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"n\n" +
	"\x12CreateOrderRequest\x12/\n" +
	"\x13vehicle_description\x18\x01 \x01(\tR\x12vehicleDescription\x12'\n" +
	"\x05items\x18\x02 \x03(\v2\x11.orders.OrderItemR\x05items\"b\n" +
	"\x18UpdateOrderStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.orders.OrderStatusR\x06status\"7\n" +
	"\x10GetOrdersRequest\x12#\n" +
	"\rstatus_filter\x18\x01 \x01(\tR\fstatusFilter\"j\n" +
	"\x12SendMessageRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1f\n" +
	"\vsender_role\x18\x03 \x01(\tR\n" +
	"senderRole\"/\n" +
	"\x12GetMessagesRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"P\n" +
	"\x14GetStatisticsRequest\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x03R\aendTime\"\x15\n" +
	"\x13GetMenuItemsRequest\">\n" +
	"\x14GetMenuItemsResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.orders.MenuItemR\x05items\"=\n" +
	"\x15UpdateMenuItemRequest\x12$\n" +
	"\x04item\x18\x01 \x01(\v2\x10.orders.MenuItemR\x04item*6\n" +
	"\vOrderStatus\x12\a\n" +
	"\x03NEW\x10\x00\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x022\xae\x04\n" +
	"\fOrderService\x12:\n" +
	"\vCreateOrder\x12\x1a.orders.CreateOrderRequest\x1a\r.orders.Order\"\x00\x12F\n" +
	"\x11UpdateOrderStatus\x12 .orders.UpdateOrderStatusRequest\x1a\r.orders.Order\"\x00\x128\n" +
	"\tGetOrders\x12\x18.orders.GetOrdersRequest\x1a\r.orders.Order\"\x000\x01\x12@\n" +
	"\vSendMessage\x12\x1a.orders.SendMessageRequest\x1a\x13.orders.ChatMessage\"\x00\x12B\n" +
	"\vGetMessages\x12\x1a.orders.GetMessagesRequest\x1a\x13.orders.ChatMessage\"\x000\x01\x12H\n" +
	"\rGetStatistics\x12\x1c.orders.GetStatisticsRequest\x1a\x17.orders.OrderStatistics\"\x00\x12K\n" +
	"\fGetMenuItems\x12\x1b.orders.GetMenuItemsRequest\x1a\x1c.orders.GetMenuItemsResponse\"\x00\x12C\n" +
	"\x0eUpdateMenuItem\x12\x1d.orders.UpdateMenuItemRequest\x1a\x10.orders.MenuItem\"\x00B.Z,git.nonahob.net/jacob/fish-fry-orders/protob\x06proto3"

var (
	file_proto_orders_proto_rawDescOnce sync.Once
	file_proto_orders_proto_rawDescData []byte
)

func file_proto_orders_proto_rawDescGZIP() []byte {
	file_proto_orders_proto_rawDescOnce.Do(func() {
		file_proto_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orders_proto_rawDesc), len(file_proto_orders_proto_rawDesc)))
	})
	return file_proto_orders_proto_rawDescData
}

var file_proto_orders_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_orders_proto_goTypes = []any{
	(OrderStatus)(0),                 // 0: orders.OrderStatus
	(*MenuItem)(nil),                 // 1: orders.MenuItem
	(*OrderItem)(nil),                // 2: orders.OrderItem
	(*Order)(nil),                    // 3: orders.Order
	(*ChatMessage)(nil),              // 4: orders.ChatMessage
	(*OrderStatistics)(nil),          // 5: orders.OrderStatistics
	(*CreateOrderRequest)(nil),       // 6: orders.CreateOrderRequest
	(*UpdateOrderStatusRequest)(nil), // 7: orders.UpdateOrderStatusRequest
	(*GetOrdersRequest)(nil),         // 8: orders.GetOrdersRequest
	(*SendMessageRequest)(nil),       // 9: orders.SendMessageRequest
	(*GetMessagesRequest)(nil),       // 10: orders.GetMessagesRequest
	(*GetStatisticsRequest)(nil),     // 11: orders.GetStatisticsRequest
	(*GetMenuItemsRequest)(nil),      // 12: orders.GetMenuItemsRequest
	(*GetMenuItemsResponse)(nil),     // 13: orders.GetMenuItemsResponse
	(*UpdateMenuItemRequest)(nil),    // 14: orders.UpdateMenuItemRequest
	nil,                              // 15: orders.OrderStatistics.ItemCountsEntry
}
var file_proto_orders_proto_depIdxs = []int32{
	2,  // 0: orders.Order.items:type_name -> orders.OrderItem
	0,  // 1: orders.Order.status:type_name -> orders.OrderStatus
	15, // 2: orders.OrderStatistics.item_counts:type_name -> orders.OrderStatistics.ItemCountsEntry
	2,  // 3: orders.CreateOrderRequest.items:type_name -> orders.OrderItem
	0,  // 4: orders.UpdateOrderStatusRequest.status:type_name -> orders.OrderStatus
	1,  // 5: orders.GetMenuItemsResponse.items:type_name -> orders.MenuItem
	1,  // 6: orders.UpdateMenuItemRequest.item:type_name -> orders.MenuItem
	6,  // 7: orders.OrderService.CreateOrder:input_type -> orders.CreateOrderRequest
	7,  // 8: orders.OrderService.UpdateOrderStatus:input_type -> orders.UpdateOrderStatusRequest
	8,  // 9: orders.OrderService.GetOrders:input_type -> orders.GetOrdersRequest
	9,  // 10: orders.OrderService.SendMessage:input_type -> orders.SendMessageRequest
	10, // 11: orders.OrderService.GetMessages:input_type -> orders.GetMessagesRequest
	11, // 12: orders.OrderService.GetStatistics:input_type -> orders.GetStatisticsRequest
	12, // 13: orders.OrderService.GetMenuItems:input_type -> orders.GetMenuItemsRequest
	14, // 14: orders.OrderService.UpdateMenuItem:input_type -> orders.UpdateMenuItemRequest
	3,  // 15: orders.OrderService.CreateOrder:output_type -> orders.Order
	3,  // 16: orders.OrderService.UpdateOrderStatus:output_type -> orders.Order
	3,  // 17: orders.OrderService.GetOrders:output_type -> orders.Order
	4,  // 18: orders.OrderService.SendMessage:output_type -> orders.ChatMessage
	4,  // 19: orders.OrderService.GetMessages:output_type -> orders.ChatMessage
	5,  // 20: orders.OrderService.GetStatistics:output_type -> orders.OrderStatistics
	13, // 21: orders.OrderService.GetMenuItems:output_type -> orders.GetMenuItemsResponse
	1,  // 22: orders.OrderService.UpdateMenuItem:output_type -> orders.MenuItem
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_orders_proto_init() }
func file_proto_orders_proto_init() {
	if File_proto_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orders_proto_rawDesc), len(file_proto_orders_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orders_proto_goTypes,
		DependencyIndexes: file_proto_orders_proto_depIdxs,
		EnumInfos:         file_proto_orders_proto_enumTypes,
		MessageInfos:      file_proto_orders_proto_msgTypes,
	}.Build()
	File_proto_orders_proto = out.File
	file_proto_orders_proto_goTypes = nil
	file_proto_orders_proto_depIdxs = nil
}
